In [1]:
import numpy as np

In [2]:
5/2

2.5

In [3]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [4]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr1*arr1

array([[ 1,  4,  9],
       [16, 25, 36]])

In [6]:
arr1 - arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
1/arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [10]:
arr1 ** 4

array([[   1,   16,   81],
       [ 256,  625, 1296]])