In [1]:
import numpy as np

In [2]:
mylist=[1,2,3]
myarray=np.array(mylist)
print(myarray)

[1 2 3]


In [3]:
myarray

array([1, 2, 3])

In [3]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [list1,list2]
array1 = np.array(list3)

In [4]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
array1.shape

(2, 3)

In [7]:
array1.dtype

dtype('int64')

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.empty(4)

array([4.66254414e-310, 0.00000000e+000, 0.00000000e+000,             nan])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [15]:
np.arange(4,20,2)

array([ 4,  6,  8, 10, 12, 14, 16, 18])