In [1]:
import numpy as np

In [2]:
arr = np.arange(0,6)

In [3]:
arr

array([0, 1, 2, 3, 4, 5])

In [5]:
arr[1:4]

array([1, 2, 3])

In [6]:
arr[0:4]

array([0, 1, 2, 3])

In [7]:
arr[0:4] = 100

In [8]:
arr

array([100, 100, 100, 100,   4,   5])

In [13]:
arr[:] = 66

In [14]:
arr

array([66, 66, 66, 66, 66, 66])

In [15]:
arr_copy = arr.copy()

In [16]:
arr_copy

array([66, 66, 66, 66, 66, 66])

In [17]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [18]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr_2d[1]

array([4, 5, 6])

In [20]:
arr_2d[2][1]

8

In [21]:
arr_2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [25]:
arr2d = np.zeros((4,4))

In [26]:
arr2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
arr2d_len = arr2d.shape[1]
arr2d_len

4

In [30]:
for i in range(arr2d_len):
    arr2d[i]=i

In [31]:
arr2d

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])