In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[2]
#output : 2 karena index dimulai dari 0

2

In [4]:
#pakai notasi [:]
arr[2:6]

array([2, 3, 4, 5])

In [6]:
#set value
arr[0:5] = 20
arr

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9])

In [8]:
#copy array
arr1 = np.arange(0,11)
arr_copy = arr1.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#array 2 dimensi
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#indexing 2 dimensi
arr2d[0]

array([1, 2, 3])

In [12]:
#cara 1
arr2d[0][1]

2

In [13]:
#cara 2
arr2d[0,1]

2

In [14]:
#pakai notasi
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [17]:
#comparion operator
bool_arr1 = arr1 > 5
bool_arr1 #array boolean

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [18]:
arr1[bool_arr1]

array([ 6,  7,  8,  9, 10])

In [20]:
arr1[arr1 < 4]

array([0, 1, 2, 3])

In [21]:
arr_2d = np.arange(0,12).reshape(3,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
arr_2d[0:1,0:2]

array([[0, 1]])

In [30]:
arr_2d[1:2,1:3]

array([[5, 6]])