In [1]:
import numpy as np

In [3]:
my_list = np.array([1,2,3,4,5])
my_list


array([1, 2, 3, 4, 5])

In [4]:
my_list1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
my_list1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
np.arange(0,11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.zeros((3,3))
# angka pertama row
# angka kedua column

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.random.rand(4)

array([0.08055468, 0.37775648, 0.54725271, 0.44964594])

In [14]:
np.random.rand(4,4)

array([[0.37274451, 0.34219929, 0.96300329, 0.38520414],
       [0.97266842, 0.86852026, 0.97075245, 0.75590773],
       [0.96097608, 0.26206102, 0.13687438, 0.80402951],
       [0.18322414, 0.74523061, 0.59695172, 0.3670576 ]])

In [15]:
np.random.randn(3,3)

array([[-0.23192022,  0.52934054,  0.14413247],
       [-0.18529028,  0.94763236, -1.19778732],
       [-1.01135552, -0.54762926, -0.73495298]])

In [17]:
np.random.randint(1,100)
#generate angka random dari 1 sampai 100

36

In [18]:
np.random.randint(1,100,10)
#generate angka random dari 1 sampai 100, 10 kali

array([ 4, 26, 12, 10,  8, 35, 42, 28, 11, 83])

In [19]:
arr = np.arange(0,25)
arr.reshape(5,5)
#reshape array ke 5x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
ran_arr = np.random.randint(1,100,10)
ran_arr.max()
#mendapatkan nilai maksimal dari array

97

In [21]:
ran_arr.min()
#mendapatkan nilai minimal dari array

16

In [22]:
ran_arr.argmax()
#mendapatkan index dari nilai maksimal dari array

4

In [23]:
ran_arr.argmin()
#mendapatkan index dari nilai minimal dari array

3

In [24]:
arr.shape
#mendapatkan ukuran dari array

(25,)

In [25]:
arr.dtype
#mendapatkan tipe data dari array

dtype('int64')